version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          config-path: .circleci/continue_config.yml
          base-revision: master
          mapping: |
            terraform/.* run-terraform true
